name: Release

on:
  push:
    tags:
      - 'v*'            # запуск только при появлении нового тега-версии

permissions:           # выдаём job'у право писать релиз
  contents: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect tags
        id: tags
        run: |
          CUR_TAG="${GITHUB_REF#refs/tags/}"
          echo "tag=$CUR_TAG" >> "$GITHUB_OUTPUT"

          PREV_TAG=$(git tag --sort=-creatordate | sed -n '2p' || true)
          echo "prev=$PREV_TAG" >> "$GITHUB_OUTPUT"

      - name: Build changelog (multiline Conventional Commits)
        id: changelog
        env:
          CUR_TAG:  ${{ steps.tags.outputs.tag }}
          PREV_TAG: ${{ steps.tags.outputs.prev }}
        run: |
          RANGE="${PREV_TAG:+$PREV_TAG..}$CUR_TAG"
          
          {                                     # открываем многострочный output
            echo "text<<CHANGELOG"
          
            # %s = subject, %n = \n, %b = body (полностью, без обрезки)
            git log --pretty=format:'- %s%n%b%n' --reverse "$RANGE" |
            # все строки, что не начинаются с «- », получат два пробела — отступ от маркера
            sed -E 's/^([^ -].*)/  \1/'
          
            echo "CHANGELOG"
          } >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name:  ${{ steps.tags.outputs.tag }}
          name:      ${{ steps.tags.outputs.tag }}
          body:      ${{ steps.changelog.outputs.text }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
