name: Release

on:
  push:
    tags:
      - 'v*'            # запуск только при появлении нового тега-версии

permissions:           # выдаём job'у право писать релиз
  contents: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect tags
        id: tags
        run: |
          CUR_TAG="${GITHUB_REF#refs/tags/}"
          echo "tag=$CUR_TAG" >> "$GITHUB_OUTPUT"

          PREV_TAG=$(git tag --sort=-creatordate | sed -n '2p' || true)
          echo "prev=$PREV_TAG" >> "$GITHUB_OUTPUT"

      - name: Build changelog
        id: changelog
        run: |
          echo "text<<CHANGELOG" >> "$GITHUB_OUTPUT"

          if [ -n "${{ steps.tags.outputs.prev }}" ]; then
            git log --pretty=format:'- %s' \
              "${{ steps.tags.outputs.prev }}..${{ steps.tags.outputs.tag }}" >> "$GITHUB_OUTPUT"
          else
            git log --pretty=format:'- %s' "${{ steps.tags.outputs.tag }}" >> "$GITHUB_OUTPUT"
          fi

          echo "" >> "$GITHUB_OUTPUT"   # пустая строка перед завершающей меткой
          echo "CHANGELOG" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name:  ${{ steps.tags.outputs.tag }}
          name:      ${{ steps.tags.outputs.tag }}
          body:      ${{ steps.changelog.outputs.text }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
